### ISSUE TITLE
当一个权重高的 Popup 在显示，后面再接着有一个权重低一点的 Popup 加入到队列，存在显示异常

### ISSUE THREAD

**Issue by jaysonjh** [HuolalaTech/hll-popupsmanager-ios#1]
1. 当一个权重高的 Popup 在显示。
2. 后面再接着有一个权重低一点的 Popup 加入到队列。
3. 权重高的 Popup dismiss 了，日志打印队列还存在一个 popup。
4. 权重低Popup 并没有弹出。

我尝试过将两个 Popup 的权重互换，权重高的后面加入队列，这种情况下是正常的，权重高的替换掉当前权重低的，等权重高的 dismiss 后权重低的再一次显示了。

**Comment by liuzhanfeng** [comment]
问题已修复
